version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=userMMM
      - POSTGRES_PASSWORD=123

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --innodb_use_native_aio=0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass