version: '3.7'
services:
  node-app:
    build: ./artifacts/gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=userMMM
      - POSTGRES_PASSWORD=123

